### ISSUE TITLE
Converting to frame process is stuck

### ISSUE THREAD

**Issue by zzw1123** [wxmahen/video-annotator#2]
Hi, 
Thanks for the quick reply!
However, after I open the MP4 video and start to convert it to images, it is stuck at 0% and the converting process seems stopped.
![image](https://user-images.githubusercontent.com/16879220/84764182-e57e4380-afff-11ea-8018-1990f33e8694.png)

Is there anything wrong?

**Comment by wxmahen** [comment]
Your OS please. Windows or Linux?
And your Java version?

**Comment by zzw1123** [comment]
Sorry I forgot...
OS: win
Java version:1.8.0_191-b12

**Comment by wxmahen** [comment]
Did you copy all the required libraries under the lib folder?

**Comment by zzw1123** [comment]
Where should I copy it?
I just open video_annotator-1.0.jar as mentioned in README.

**Comment by wxmahen** [comment]
This is the folder structure.
https://github.com/wxmahen/video-annotator/tree/master/running_programs/windows

**Comment by zzw1123** [comment]
Yes, mine has the same structure as yours.
![image](https://user-images.githubusercontent.com/16879220/84781580-95ac7600-b019-11ea-9915-6100716b183b.png)
and there are 18 jar files under lib file:
![image](https://user-images.githubusercontent.com/16879220/84781624-a6f58280-b019-11ea-8176-116c25d0a4fc.png)

**Comment by wxmahen** [comment]
I added error messages. Please download the new version and try. Comment here the error message you get.

**Comment by zzw1123** [comment]
Hi, I download the newest code and it is still stuck at 0%.
Where does the error message show on?

**Comment by zzw1123** [comment]
And, are there any methods to check whether my environment is correctly configured?

**Comment by zzw1123** [comment]
I found that there is something wrong with my JAVA environment......
After I fix it, the converting process goes smoothly!
Thanks for the excellent job and your patience!

**Comment by wxmahen** [comment]
Great. Thank you.
